Dockerfile_V3/CV-Django-Deploy-Docker/Cv_Personal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('formacion_academica/', views.Shesst2_CV.as_view(), name='formacion_academica'),
    path('formacion_academica_ce/', views.Shesst3_CV.as_view(), name='formacion_academica_ce'),
    path('formacion_academica_ct/', views.Shesst4_CV.as_view(), name='formacion_academica_ct'),
    path('experiencia/', views.Shesst5_CV.as_view(), name='experiencia'),

    #path('skills/', include('skills.urls', namespace='skills')),
    path('', include('skills.urls')),
    path('', include('FormAcad.urls')),
    path('', include('FormEsp.urls')),
    path('', include('Certificados.urls')),
    path('', include('Experience.urls')),
    path('', include('actividad_adicional.urls')),


] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Dockerfile_V3/CV-Django-Deploy-Docker/accounts/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup')
]

Dockerfile_V3/CV-Django-Deploy-Docker/skills/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views

#app_name = 'skills'

urlpatterns = [
    path('habilidades/', views.Test_Skills.as_view(), name='habilidades'),
]

Dockerfile_V3/CV-Django-Deploy-Docker/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jorge Guevara</title>
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    {% comment %} <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> {% endcomment %}

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    
    <link href="https://fonts.googleapis.com/css2?family=Montserrat" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'Cv_Personal/css/master.css' %}">


</head>
<body class = "header-body">

    {% comment %} <nav class = 'navbar mynav' role = 'navigation' id = 'navbar'>
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="">Post</a></li>
                    <li><a href="">Groups</a></li>
                    <li><a href="">Create Group</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a href="">Groups</a></li>
                    <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}

            </ul>

        </div>

    </nav> {% endcomment %}

    <!-- DOCUMENTATION NAVBAR -->

  <nav class="navbar navbar-default navbar-inverse navbar-fixed-top mynav ">

      <!-- Inside of a Container -->
    <div class="container">

      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- This is the actual code that create the "hamburger icon" -->
      <!-- The data-target grabs ids to put into the icon -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

          <!--  Code for the hamburger icon-->
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="{% url 'home' %}">Jorge Guevara</a>
      </div>

      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="">Post</a></li>
                <li><a href="https://github.com/mamuts1532">GitHub</a></li>
                <li><a href="https://www.linkedin.com/in/jorge-ivan-guevara-perez/">LinkedIn</a></li>
                <!-- Use this to separate a new link -->
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
            {% else %}
                {% comment %} <li><a href="">Groups</a></li> {% endcomment %}
                <li><a href="https://www.linkedin.com/in/jorge-ivan-guevara-perez/">LinkedIn</a></li>
                <li><a href="https://github.com/mamuts1532/">GitHub</a></li>
                <!-- Use this to separate a new link -->
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Curriculum <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/habilidades">Habilidades</a></li>

                    <!-- Use this to separate a new link -->

                    <li role="separator" class="divider"></li>
                    <li><a href="/experience">Experiencia</a></li>
                    <li><a href="/formacad">Formacion Academica</a></li>
                    <li><a href="/formesp">Formacion Especializada</a></li>
                    <li><a href="/certificados">Certificados</a></li>

                  </ul>
                </li>
                {% comment %} <li><a href="{% url 'accounts:login' %}">Log In</a></li>
                <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li> {% endcomment %}
            {% endif %}

        </ul>        

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

  <div class="container">



    <div class="row">
      <div class="col-sm-8 blog-main">

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>

      </div><!-- /.blog-main -->
          <div class = "cv-header-sidebar">
              <img src="/media/jorge_guevara.jpg" alt="Jorge Guevara" class = "image-center-sidebar">      
          </div>
          <div class = "center">
              <h4>Jorge Ivan Guevara Pérez</h4>
              <h5>Consultor e Investigador TI</h5>
          </div>


      <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        <div class="sidebar-module sidebar-module-inset">
          <h4>Acerca de mí</h4>
          <p>Esposo, padre de familia, emprendedor, autónomo, disciplinado, responsable y comprometido.</p>
        </div>
        <div class="sidebar-module">
          <h4>Enlaces</h4>
          <ol class="list-unstyled">
            <li><a href="/habilidades">Habilidades</a></li>
            <li><a href="/experience">Experiencia</a></li>
            <li><a href="/formacad">Formacion Academica</a></li>
            <li><a href="/formesp">Formacion Especializada</a></li>
            <li><a href="/certificados">Certificados</a></li>
            <li><a href="/actividad_adicional">Actividades Adicionales</a></li>
          </ol>
        </div>
        <div class="sidebar-module">
          <h4>Sígueme</h4>
          <ol class="list-unstyled">
            <li><a href="https://github.com/mamuts1532">GitHub</a></li>
            <li><a href="https://www.linkedin.com/in/jorge-ivan-guevara-perez/">LinkedIn</a></li>
          </ol>
        </div>
      </div><!-- /.blog-sidebar -->

    </div><!-- /.row -->

  </div><!-- /.container -->





  <footer class="blog-footer" style="background-color: #212121">
    <p>Copyright @ Jorge Guevara 2021</p>
    <p>
      <a href="#">Volver al inicio</a>
    </p>
  </footer>

  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  <script
  src="https://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


</body>
</html>

Dockerfile_V3/CV-Django-Deploy-Docker/templates/index.html
{% extends "base.html" %}
{% block content %}


    <div class="container">

    {% comment %} <div class = "cv-header">
        <img src="/media/jorge_guevara.jpg" alt="Jorge Guevara" class = "image-center">      
    </div>
    <div class = "center">
        <h3>Jorge Ivan Guevara Pérez</h3>
        <h4>Consultor TI</h4>
    </div> {% endcomment %}

      <div class="row">
        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">PRESENTACIÓN</h2>
            <p class="blog-post-meta">{% now "j F Y g:i a" %}</p>



            <p align="justify">Consultor e investigador de tecnología con experiencia en gestión de recursos en la nube 
            usando plataforma como Google Cloud Platform y Azure, manejo de infraestructura de tecnología para proyectos 
            de ciencia y minería de datos. Habilidades para carga, almacenaje y manipulación de datos en herramientas 
            como Hadoop (Cloudera) y Bases de datos relacionales y no relacionales. 
            <br>
            <blockquote>
              <p>Gestión de recursos en la nube usando plataformas como <strong>Google Cloud Platform</strong> y <strong>Azure</strong>.</p>
            </blockquote>
          
            <p align="justify">Analista enfocado en la extracción, limpieza, manipulación y visualización de datos para la 
            ejecución de técnicas cómo machine learning, clustering, minería de datos, análisis de texto, 
            visualización y rastreo web con Python. Desarrollador Full Stack con frameworks de Python para el desarrollo 
            de aplicaciones.
            <br>
            <blockquote>
              <p>Desarrollador Full Stack con frameworks de <strong>Python</strong> para el desarrollo de aplicaciones.</p>
            </blockquote>
            <p align="justify">Responsable, autónomo y muy meticuloso. Altamente comprometido con el cumplimiento del deber y los valores. 
            Como independiente he desempeñado cargos en gerencia y administración de empresas del sector comercial y 
            financiero, relacionado con corresponsal bancario y compra/venta profesional de divisas, he recibido capacitación 
            para el cumplimiento del SARLAFT y la creación y manejo de informes para reportes a la UIAF
            .</p>
            <hr>


          </div><!-- /.blog-post -->

          <div class="blog-post">
            <h2 class="blog-post-title">DATOS PERSONALES</h2>

            <p style="text-align:left; font-size:16px;"><strong>Fecha y Lugar de Nacimiento:</strong> <span style="float:right;">24 de Noviembre de 1984, Bucaramanga Santander</span></p>
            {% comment %} <p style="text-align:left; font-size:16px;"><strong>Documento De Identidad:</strong> <span style="float:right;">C.C. XXXXXXXXXXX</span></p> {% endcomment %}
            <p style="text-align:left; font-size:16px;"><strong>Tarjeta Profesional:</strong> <span style="float:right;">No. NS290-63296</span></p>
          </div><!-- /.blog-post -->

        <nav>
          <ul class="pager">
            <li><a href="#">Previo</a></li>
            <li><a href="{% url 'habilidades' %}">Siguiente</a></li>
          </ul>
        </nav>
        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
        
        {% comment %} <div class = "cv-header-sidebar">
            <img src="/media/jorge_guevara.jpg" alt="Jorge Guevara" class = "image-center-sidebar">      
        </div>
        <div class = "center">
            <h4>Jorge Ivan Guevara Pérez</h4>
            <h5>Consultor TI</h5>
        </div> {% endcomment %}
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->
    </div>


{% endblock %}